# --- CONFIGURATION DE BASE REQUISE ---
baseURL = "https://AntoineWHR.github.io/mon-blog-final/" # <--- VÉRIFIE BIEN CETTE URL !
languageCode = "fr-fr" # Ou "en-us", etc.
title = "Mon Blog Final - CyberSec" # <--- METS LE TITRE DE TON SITE
theme = "LoveIt"
mainSections = ["posts"]
# Thème par défaut (évite le flash au chargement)
defaultContentLanguage = "fr" # Mets le code de ta langue principale
hasCJKLanguage = false # Met à 'true' si tu écris en Chinois/Japonais/Coréen

# --- Configuration de Langue (même si une seule) ---
[languages]
  [languages.fr] # Utilise ton code langue (ex: 'en' si anglais)
    languageName = "Français" # Nom de la langue
    weight = 1
    # Tu peux surcharger des params spécifiques à la langue ici si besoin

# --- Paramètres du Thème LoveIt ---
[params]
  # Description du site (pour les moteurs de recherche)
  description = "Partage de connaissances et writeups sur la cybersécurité." # <--- METS TA DESCRIPTION
  # Auteur du site (important pour le thème)
  [params.author]
    name = "AntoineWHR" # <--- METS TON NOM/PSEUDO

  # Configuration de l'en-tête
  [params.header]
    desktopMode = "fixed" # Comportement du header sur PC
    mobileMode = "auto" # Comportement du header sur mobile
    [params.header.title]
      # logo = "/images/logo.png" # Chemin vers ton logo si tu en as un (dans /static/images/)
      name = "AntoineWHR - CyberSec Blog" # Texte affiché dans l'en-tête <--- METS LE TEXTE VOULU
      pre = "" # Texte/icône avant le nom
      post = "" # Texte/icône après le nom

  # Configuration du pied de page
  [params.footer]
    enable = true
    hugo = true # Affiche "Powered by Hugo"
    copyright = true # Affiche © Année Auteur
    author = true # Affiche l'auteur
    since = 2024 # Année de création du site <--- METS L'ANNEE ACTUELLE

  # Configuration du mode sombre/clair
  [params.theme]
    defaultTheme = "auto" # 'auto', 'light', 'dark'
    # themeColor = "#Classy" # Schéma de couleurs LoveIt (voir doc)

  # Liens sociaux (ajoute ceux que tu veux)
  [params.social]
    GitHub = "AntoineWHR" # <--- METS TON PSEUDO GITHUB
    # Linkedin = "tonprofil"
    # Twitter = "tonpseudo"
    # Email = "contact@example.com"

  # Autres paramètres utiles pour LoveIt
  [params.page]
    toc = true # Activer la table des matières par défaut sur les articles
    [params.page.code]
        # maxShownLines = 10 # Limite lignes affichées par défaut bloc code
    [params.page.comment]
        enable = false # Désactiver les commentaires par défaut

# --- MENUS ---
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles" # Texte du lien
    url = "/posts/" # Chemin vers la liste des articles
    weight = 10 # Ordre d'affichage
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "Catégories"
    url = "/categories/"
    weight = 30
  # Décommente quand tu auras une page "À Propos"
  # [[menu.main]]
  #   identifier = "about"
  #   name = "À Propos"
  #   url = "/about/"
  #   weight = 40

# --- Nécessaire pour certaines fonctionnalités (Recherche LoveIt, etc.) ---
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# --- Configuration du Markdown ---
[markup]
  [markup.highlight]
    # Style de coloration syntaxique (voir doc Hugo)
    # style = "dracula"
    noClasses = false # Important pour LoveIt
  [markup.goldmark.renderer]
    unsafe = true # Permet le HTML dans le Markdown (utile parfois)
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

# --- Taxonomies (Tags, Catégories) ---
[taxonomies]
  category = "categories"
  tag = "tags"
  # series = "series" # Si tu veux regrouper des articles en séries
