# --- CONFIGURATION DE BASE REQUISE ---
baseURL = "https://AntoineWHR.github.io/mon-blog-final/" # <--- VÉRIFIE BIEN CETTE URL !
languageCode = "fr-fr" # Ou "en-us", etc.
title = "Antoine Garcia - WheelRoot" # <--- METS LE TITRE DE TON SITE
theme = "LoveIt"
mainSections = ["posts"]
# Thème par défaut (évite le flash au chargement)
defaultContentLanguage = "fr" # Mets le code de ta langue principale
hasCJKLanguage = false # Met à 'true' si tu écris en Chinois/Japonais/Coréen

# --- Configuration de Langue (même si une seule) ---
[languages]
  [languages.fr] # Utilise ton code langue (ex: 'en' si anglais)
    languageName = "Français" # Nom de la langue
    weight = 1
    # Tu peux surcharger des params spécifiques à la langue ici si besoin

# --- Paramètres du Thème LoveIt ---
[params]
  # Description du site (pour les moteurs de recherche)
  description = "Partage de connaissances et writeups sur la cybersécurité." # <--- METS TA DESCRIPTION
  # Auteur du site (important pour le thème)
  [params.author]
    name = "AntoineWHR" # <--- METS TON NOM/PSEUDO

  # Configuration de l'en-tête (barre de navigation principale)
  [params.header]
    desktopMode = "fixed" # Comportement du header sur PC
    mobileMode = "auto" # Comportement du header sur mobile
    [params.header.title]
      # logo = "/images/who.png" # Commenté : Ce n'est PAS l'avatar du profil
      name = "Antoine Garcia - WheelRoot" # Texte affiché dans l'en-tête
      pre = "" # Texte/icône avant le nom
      post = "" # Texte/icône après le nom

  # Configuration du pied de page
  [params.footer]
    enable = true
    hugo = true # Affiche "Powered by Hugo"
    copyright = true # Affiche © Année Auteur
    author = true # Affiche l'auteur
    since = 2024 # Année de création du site

  # Configuration du mode sombre/clair
  [params.theme]
    defaultTheme = "auto" # 'auto', 'light', 'dark'
    # themeColor = "#Classy" # Schéma de couleurs LoveIt (voir doc)

  # Liens sociaux (affichés sous le profil si social = true ci-dessous)
  [params.social]
    GitHub = "AntoineWHR" # <--- METS TON PSEUDO GITHUB
    # Linkedin = "tonprofil"
    # Twitter = "tonpseudo"
    # Email = "contact@example.com"

  # --- Section Profil de la Page d'Accueil --- <<< AJOUT/MODIFICATION ICI
  [params.home]
    [params.home.profile]
      enable = true       # <<< Active le bloc profil
      gravatarEmail = ""  # <<< Laisse vide pour utiliser l'avatar local
      avatar = "images/who.png" # <<< CHEMIN vers ton avatar (depuis la racine du site)
      title = "AntoineWHR" # <<< Le nom/pseudo à afficher DANS LE BLOC PROFIL
      subtitle = "Explorateur du Cyberespace | Write-ups, Projets, CTF" # <<< Le texte qui tape
      typeit = true       # <<< Active l'effet "machine à écrire"
      social = true       # <<< Affiche les liens sociaux (configurés dans [params.social])

  # --- Paramètres des pages (articles, etc.) --- <<< CORRECTION DE STRUCTURE ICI
  [params.page] # 'toc' doit être dans 'page'
    [params.page.toc]  # Définit 'toc' comme une table (objet)
      enable = true      # Active la Table des Matières par défaut
      # keepStatic = false
      # auto = true
    [params.page.code]
        # maxShownLines = 10
    [params.page.comment]
        enable = false

# --- MENUS ---
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "Catégories"
    url = "/categories/"
    weight = 30
  # [[menu.main]]
  #   identifier = "about"
  #   name = "À Propos"
  #   url = "/about/"
  #   weight = 40

# --- OUTPUTS ---
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# --- MARKUP ---
[markup]
  [markup.highlight]
    # style = "dracula"
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

# --- TAXONOMIES ---
[taxonomies]
  category = "categories"
  tag = "tags"
  # series = "series"
